### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by klartext** [pippijn/aldor#118]
see here:
http://sprunge.us/EiXW

**Comment by pippijn** [comment]
We require bison. Byacc won't work for now.

**Comment by klartext** [comment]
configure --help
mentions byacc as one of three allowed alternatives.

**Comment by klartext** [comment]
Switched to bison.
Compilation fails.
See here:
http://sprunge.us/EJbS

**Comment by iphydf** [comment]
Try `./configure --disable-error-on-warning`.

**Comment by pippijn** [comment]
Try `./configure --disable-error-on-warning`.

**Comment by klartext** [comment]
Thanks, that works now. Compilation succeeded. :-)
