### ISSUE TITLE
Bring back support for macOS?

### ISSUE THREAD

**Issue by LdBeth** [pippijn/aldor#134]
Getting the compiler itself builds using `clang` and compiles the library files on macOS is not hard since the platform specific code was already there. There're some issues worth notice:

1. `brk()` is marked as depreciated by `clang` thus `CFLAGS="-Wno-error=deprecated-declarations"` has to be used. Also `clang` complains a lot on "Control may reach end of non-void function." which may needs to be fixed.

2. Instead of `CLOCK_PER_SECOND` used in [time.h0](https://github.com/pippijn/aldor/blob/14b25da05c0651d91c46f87194aa4689d7431ebf/aldor/aldor/src/time.h0), POSIX `<time.h>` defines `CLOCKS_PER_SEC`

3. linking has some trouble that `ld` complains `symbol(s) not found for architecture x86_64`, adding corresponding object file that contains the symbols to `LDADD` do get rid of this kind of problems. <ins>Possibly due to `ar` difference.</ins>

4. definitions in [os_macosx_vm.c](https://github.com/pippijn/aldor/blob/master/aldor/aldor/src/os_macosx_vm.c) need updates to match new versions of macOS SDKs

 However the current building script assumes GNU binutils `ar` which has different behavior than the BSD style one that macOS has, particularly the BSD `ar` doesn't allow create empty archive or pass no file to be added to existed archive, and I doubt the formats used by the two `ar` programs do differ.

**Comment by LdBeth** [comment]
by create the empty `.al` files by hand I can build `src/libfoamlib` but hitting problem on`src/libfoam`,

when `ALDOR  domain.ao` the compiler cannot recognize some identifiers

```
  ALDOR  dispatchvector.ao
  ALDOR  domain.ao
"domain.as", line 40:         new: (DispatchVector, DomainRep) -> %;
                      ..............^
[L40 C15] #1 (Error) No meaning for identifier `DispatchVector'.
[L40 C15] #5 (Error) Argument 1 of `->' did not match any possible parameter type.
    Expected type Tuple(Type).

"domain.as", line 81: 
        reFill!:        (%, DispatchVector, DomainRep) -> ();
.........................^
[L81 C26] #3 (Error) Argument 1 of `->' did not match any possible parameter type.
    Expected type Tuple(Type).

"domain.as", line 85:         Rep ==> Record (dispatcher:     DispatchVector, 
                      ........................^...............^
[L85 C25] #10 (Error) (After Macro Expansion) Argument 1 of `Record' did not match any possible parameter type.
    Expected type Type.
Expanded expression was: dispatcher: DispatchVector
[L85 C41] #9 (Error) (After Macro Expansion) No meaning for identifier `DispatchVector'.
Expanded expression was: DispatchVector

"domain.as", line 190: makeDomain(dv: DispatchVector, r: DomainRep): Domain ==
                       ...........^...^
[L190 C12] #7 (Error) Have determined 1 possible types for the expression.
	Meaning 1: ?, Join(
                 with 
                    ==  add ()...
  The context requires an expression of type Tuple(Type).
[L190 C12] #8 (Error) Argument 1 of `->' did not match any possible parameter type.    The rejected type is ?, Join(
                 with 
                    ==  add ()....
    Expected type Tuple(Type).
[L190 C16] #6 (Error) No meaning for identifier `DispatchVector'.
[L190 C16] #11 (Fatal Error) Too many errors (use `-M emax=n' or `-M no-emax' to change the limit).

make: *** [domain.ao] Error 1
```

I think it's not `aldor` cannot read `al` files created by BSD `ar` since `src/libfoam` already successes. Did I missed something?

**Comment by LdBeth** [comment]
not sure if could be the cause to the problem above, but make `.dep` files in `libfoam` results in weird file contents.

```
$ cat runtime.dep
basictuple
basictuple
box
dispatchvector
domain
basictuple
basictuple
basictuple
box
dispatchvector
domain
basictuple
basictuple
basictuple
box
dispatchvector
domain
box
basictuple
basictuple
box
dispatchvector
domain
catdispatchvector
basictuple
ptrcache
catobj
stringtable
aldordomainrep
basictuple
box
basictuple
basictuple
box
dispatchvector
domain
catdispatchvector
basictuple
basictuple
basictuple
box
dispatchvector
domain
box
basictuple
basictuple
box
dispatchvector
domain
catdispatchvector
basictuple
ptrcache
catobj
stringtable
aldorcatrep
box
basictuple
basictuple
box
dispatchvector
domain
catdispatchvector
basictuple
basictuple
basictuple
box
dispatchvector
domain
box
basictuple
basictuple
box
dispatchvector
domain
catdispatchvector
basictuple
ptrcache
catobj
ptrcatobj
basictuple
basictuple
box
dispatchvector
basictuple
basictuple
box
dispatchvector
domain
pointerdomain
box
basictuple
basictuple
box
dispatchvector
domain
lazyimport
basictuple
ptrcache
```

**Comment by pbroadbery** [comment]
thankyou for the patch  - Assuming it works, please create a pull request and it can be merged.
The travis config should be extended to include macos, which should keep it honest in the future.

**Comment by LdBeth** [comment]
see PR #136

**Comment by pbroadbery** [comment]
I've had a go at getting travis to wok with macos and your patch, but can't get the link steps to work.. - see PR #137  
Is there something I've missed ?

**Comment by LdBeth** [comment]
I've made these changes to resolve linking problem specifically. 

https://github.com/pippijn/aldor/pull/136/commits/5b999b02ac363f5af1d582dacd4dc3ee92283113

No exact idea on how `libtool` things work on macOS though.
