### ISSUE TITLE
When building from git, configure should warn or take appropriate action when lex & yacc not found

### ISSUE THREAD

**Issue by rocky** [pippijn/aldor#139]
I built aldor form source the other day. I didn't have lex/flex installed and so the compile failed. 

Addressing the problem seems pretty straightforward. 

Here is one idea: In `autogen.sh` run `configure` afterwards with `--enable-maintainer-mode`. Then inside configure give an error if either Lex or YACC (any version) is not found.

Alternatively, some fairly recent version of the output of Lex and YACC could be put in the repositoyr used (or if desired copied form a separate backup file) when one of the programs that generates the file isn't around. That way, the `Makefile` mechanism will still  work and update the derived files, but the need for either Lex or YACC isn't a hard requirement when building from git sources., 

If there is interest, I can put in a PR for this.

What do you thinK?

**Comment by pbroadbery** [comment]
I'd be happy with either, but my slight preference would be for them to be
required (maintaner mode or not), and configure fails if they are not
installed.
That preference could very easily be swayed by a PR in the other direction,
and I'd be happy to see one.

Peter

**Comment by rocky** [comment]
> I'd be happy with either, but my slight preference would be for them to be required (maintaner mode or not), and configure fails if  they are not installed.

Ok. On the theory of do the least thing that gets the job done, PR #140 is in which does just this. The change to do this IMHO is pretty small and simple. But if there are changes you want, maintainers should be able to just made edits to the PR, so please do!
