### ISSUE TITLE
segfault when using "aldorio" in interactive mode

### ISSUE THREAD

**Issue by edi-meier** [pippijn/aldor#17]
$ aldor -gloop
%1 >> #include "aldor"
%2 >> #include "aldorio"
%3 >> import from Integer
%4 >> 1+1
Program fault (segmentation violation).#2 (Error) Program fault (segmentation violation).
#1 (Error) No meaning for identifier `print'.

Does not segfault if called via 'aldor -grun -laldor one.as'

**Comment by pbroadbery** [comment]
Fixed in 1.3
